[ayucloud.services]
auth_path  user
auto_invite  F
buy  pass
email  wjtzncrcz19@grr.la
last_checkin  2025-05-01 18:21:35.271376+08:00
name  AyucLouD-Services
node_n  99
sub_info  0B  0B  2025-05-02 18:21:34+08:00  (剩余 0B -1 day, 3:35:14.040974)
sub_url  https://network.ayucloud.nl/link/NIVOHItvlbTkZkpV?clash=1
time  2025-05-01 18:21:36.298653+08:00
type  sspanel
保存base64/clash订阅失败  'NoneType' object is not iterable
尝试签到失败  HTTPSConnectionPool(host='ayucloud.services', port=443): Max retries exceeded with url: /user/login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6ca6ef5c60>, 'Connection to ayucloud.services timed out. (connect timeout=30)'))
更新旧订阅失败  HTTPSConnectionPool(host='ayucloud.services', port=443): Max retries exceeded with url: /user/login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6ca6f828c0>, 'Connection to ayucloud.services timed out. (connect timeout=30)'))

[qlgq.top]

[cyanmori.com]

[vipxgyun.com]
